//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dhmi.Web.SmsService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsService.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reportSmsSummary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet reportSmsSummary(string username, string password, string startdate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSmsDetailFromIDList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dhmi.Web.SmsService.Sms[] getSmsDetailFromIDList(string username, string password, string msgid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSmsDetailFromIDListbyStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dhmi.Web.SmsService.Sms[] getSmsDetailFromIDListbyStatus(string username, string password, string msgid, int BekleyenleriGetir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reportSmsSummaryList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dhmi.Web.SmsService.SmsPaket[] reportSmsSummaryList(string username, string password, string startdate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSmsOriginatorListbyList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] getSmsOriginatorListbyList(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSmsDetailFromID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getSmsDetailFromID(string username, string password, string msgid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSmsOriginatorList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getSmsOriginatorList(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSMSCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getSMSCredit(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTTKontor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dhmi.Web.SmsService.TTQuota getTTKontor(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendSingleSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string sendSingleSMS(string username, string password, string numbers, string message, string origin, string sd, string ed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendSingleSMSEndDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string sendSingleSMSEndDate(string username, string password, string numbers, string message, string origin, string sd, string ed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendSingleSMSXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string sendSingleSMSXML(string username, string password, string XML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendNtoNSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string sendNtoNSMS(string username, string password, string xmData, string origin, string sd, string ed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DLL_ALICI_EKLE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DLL_ALICI_EKLE(string username, string password, string xmData, string _mesajXML, string _MsgTime, string _startDateXML, string origin, int msgcount, int SPCallNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendSMSbyInteractive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void sendSMSbyInteractive(string ACODE, string UCODE, string Message, string senderGSM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendSingleSMSobj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dhmi.Web.SmsService.SmsSonuc sendSingleSMSobj(string username, string password, string numbers, string message, string origin, string sd, string ed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendNtoNSMSobjobjeski", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dhmi.Web.SmsService.SmsSonuc sendNtoNSMSobjobjeski(string username, string password, string xmData, string origin, string sd, string ed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendNtoNSMSobj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dhmi.Web.SmsService.SmsSonuc sendNtoNSMSobj(string username, string password, string xmData, string origin, string sd, string ed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dhmi.Web.SmsService.Kisi GetUserInfo(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSubUserList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dhmi.Web.SmsService.KisiAlt[] GetSubUserList(string username, string password);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sms : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int servisHataField;
        
        private string idField;
        
        private string paketIdField;
        
        private string gonderimTarihField;
        
        private string ulasimTarihField;
        
        private string originField;
        
        private string aliciField;
        
        private int mesajUzunluğuField;
        
        private int gonderimDurumField;
        
        private string gonderimDurumAciklamaField;
        
        private string icerikField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ServisHata {
            get {
                return this.servisHataField;
            }
            set {
                this.servisHataField = value;
                this.RaisePropertyChanged("ServisHata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PaketId {
            get {
                return this.paketIdField;
            }
            set {
                this.paketIdField = value;
                this.RaisePropertyChanged("PaketId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GonderimTarih {
            get {
                return this.gonderimTarihField;
            }
            set {
                this.gonderimTarihField = value;
                this.RaisePropertyChanged("GonderimTarih");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UlasimTarih {
            get {
                return this.ulasimTarihField;
            }
            set {
                this.ulasimTarihField = value;
                this.RaisePropertyChanged("UlasimTarih");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
                this.RaisePropertyChanged("Origin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Alici {
            get {
                return this.aliciField;
            }
            set {
                this.aliciField = value;
                this.RaisePropertyChanged("Alici");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int MesajUzunluğu {
            get {
                return this.mesajUzunluğuField;
            }
            set {
                this.mesajUzunluğuField = value;
                this.RaisePropertyChanged("MesajUzunluğu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int GonderimDurum {
            get {
                return this.gonderimDurumField;
            }
            set {
                this.gonderimDurumField = value;
                this.RaisePropertyChanged("GonderimDurum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string GonderimDurumAciklama {
            get {
                return this.gonderimDurumAciklamaField;
            }
            set {
                this.gonderimDurumAciklamaField = value;
                this.RaisePropertyChanged("GonderimDurumAciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Icerik {
            get {
                return this.icerikField;
            }
            set {
                this.icerikField = value;
                this.RaisePropertyChanged("Icerik");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KisiAlt : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int servisHataField;
        
        private string kullaniciAdiField;
        
        private string unvanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ServisHata {
            get {
                return this.servisHataField;
            }
            set {
                this.servisHataField = value;
                this.RaisePropertyChanged("ServisHata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string KullaniciAdi {
            get {
                return this.kullaniciAdiField;
            }
            set {
                this.kullaniciAdiField = value;
                this.RaisePropertyChanged("KullaniciAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Unvan {
            get {
                return this.unvanField;
            }
            set {
                this.unvanField = value;
                this.RaisePropertyChanged("Unvan");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Originn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string originNameField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OriginName {
            get {
                return this.originNameField;
            }
            set {
                this.originNameField = value;
                this.RaisePropertyChanged("OriginName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Kisi : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int servisHataField;
        
        private string unvanField;
        
        private string kontorField;
        
        private string sMSTipField;
        
        private Originn[] originListField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ServisHata {
            get {
                return this.servisHataField;
            }
            set {
                this.servisHataField = value;
                this.RaisePropertyChanged("ServisHata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Unvan {
            get {
                return this.unvanField;
            }
            set {
                this.unvanField = value;
                this.RaisePropertyChanged("Unvan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Kontor {
            get {
                return this.kontorField;
            }
            set {
                this.kontorField = value;
                this.RaisePropertyChanged("Kontor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SMSTip {
            get {
                return this.sMSTipField;
            }
            set {
                this.sMSTipField = value;
                this.RaisePropertyChanged("SMSTip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public Originn[] OriginList {
            get {
                return this.originListField;
            }
            set {
                this.originListField = value;
                this.RaisePropertyChanged("OriginList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SmsSonuc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sonucField;
        
        private string kontorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Sonuc {
            get {
                return this.sonucField;
            }
            set {
                this.sonucField = value;
                this.RaisePropertyChanged("Sonuc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Kontor {
            get {
                return this.kontorField;
            }
            set {
                this.kontorField = value;
                this.RaisePropertyChanged("Kontor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TTQuota : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string servisHataField;
        
        private int amountField;
        
        private int extIDField;
        
        private string expireTimeField;
        
        private int initialAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServisHata {
            get {
                return this.servisHataField;
            }
            set {
                this.servisHataField = value;
                this.RaisePropertyChanged("ServisHata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ExtID {
            get {
                return this.extIDField;
            }
            set {
                this.extIDField = value;
                this.RaisePropertyChanged("ExtID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ExpireTime {
            get {
                return this.expireTimeField;
            }
            set {
                this.expireTimeField = value;
                this.RaisePropertyChanged("ExpireTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int InitialAmount {
            get {
                return this.initialAmountField;
            }
            set {
                this.initialAmountField = value;
                this.RaisePropertyChanged("InitialAmount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SmsPaket : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int servisHataField;
        
        private string paketIdField;
        
        private string icerikField;
        
        private string originField;
        
        private int mesajUzunluğuField;
        
        private int mesajAdetiField;
        
        private string gonderimTarihField;
        
        private int İletilenField;
        
        private int bekleyenField;
        
        private int hataliField;
        
        private int zamanAsimiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ServisHata {
            get {
                return this.servisHataField;
            }
            set {
                this.servisHataField = value;
                this.RaisePropertyChanged("ServisHata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PaketId {
            get {
                return this.paketIdField;
            }
            set {
                this.paketIdField = value;
                this.RaisePropertyChanged("PaketId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Icerik {
            get {
                return this.icerikField;
            }
            set {
                this.icerikField = value;
                this.RaisePropertyChanged("Icerik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
                this.RaisePropertyChanged("Origin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int MesajUzunluğu {
            get {
                return this.mesajUzunluğuField;
            }
            set {
                this.mesajUzunluğuField = value;
                this.RaisePropertyChanged("MesajUzunluğu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int MesajAdeti {
            get {
                return this.mesajAdetiField;
            }
            set {
                this.mesajAdetiField = value;
                this.RaisePropertyChanged("MesajAdeti");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string GonderimTarih {
            get {
                return this.gonderimTarihField;
            }
            set {
                this.gonderimTarihField = value;
                this.RaisePropertyChanged("GonderimTarih");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int İletilen {
            get {
                return this.İletilenField;
            }
            set {
                this.İletilenField = value;
                this.RaisePropertyChanged("İletilen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Bekleyen {
            get {
                return this.bekleyenField;
            }
            set {
                this.bekleyenField = value;
                this.RaisePropertyChanged("Bekleyen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int Hatali {
            get {
                return this.hataliField;
            }
            set {
                this.hataliField = value;
                this.RaisePropertyChanged("Hatali");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int ZamanAsimi {
            get {
                return this.zamanAsimiField;
            }
            set {
                this.zamanAsimiField = value;
                this.RaisePropertyChanged("ZamanAsimi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Dhmi.Web.SmsService.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Dhmi.Web.SmsService.Service1Soap>, Dhmi.Web.SmsService.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet reportSmsSummary(string username, string password, string startdate, string enddate) {
            return base.Channel.reportSmsSummary(username, password, startdate, enddate);
        }
        
        public Dhmi.Web.SmsService.Sms[] getSmsDetailFromIDList(string username, string password, string msgid) {
            return base.Channel.getSmsDetailFromIDList(username, password, msgid);
        }
        
        public Dhmi.Web.SmsService.Sms[] getSmsDetailFromIDListbyStatus(string username, string password, string msgid, int BekleyenleriGetir) {
            return base.Channel.getSmsDetailFromIDListbyStatus(username, password, msgid, BekleyenleriGetir);
        }
        
        public Dhmi.Web.SmsService.SmsPaket[] reportSmsSummaryList(string username, string password, string startdate, string enddate) {
            return base.Channel.reportSmsSummaryList(username, password, startdate, enddate);
        }
        
        public string[] getSmsOriginatorListbyList(string username, string password) {
            return base.Channel.getSmsOriginatorListbyList(username, password);
        }
        
        public string getSmsDetailFromID(string username, string password, string msgid) {
            return base.Channel.getSmsDetailFromID(username, password, msgid);
        }
        
        public string getSmsOriginatorList(string username, string password) {
            return base.Channel.getSmsOriginatorList(username, password);
        }
        
        public string getSMSCredit(string username, string password) {
            return base.Channel.getSMSCredit(username, password);
        }
        
        public Dhmi.Web.SmsService.TTQuota getTTKontor(string username, string password) {
            return base.Channel.getTTKontor(username, password);
        }
        
        public string sendSingleSMS(string username, string password, string numbers, string message, string origin, string sd, string ed) {
            return base.Channel.sendSingleSMS(username, password, numbers, message, origin, sd, ed);
        }
        
        public string sendSingleSMSEndDate(string username, string password, string numbers, string message, string origin, string sd, string ed) {
            return base.Channel.sendSingleSMSEndDate(username, password, numbers, message, origin, sd, ed);
        }
        
        public string sendSingleSMSXML(string username, string password, string XML) {
            return base.Channel.sendSingleSMSXML(username, password, XML);
        }
        
        public string sendNtoNSMS(string username, string password, string xmData, string origin, string sd, string ed) {
            return base.Channel.sendNtoNSMS(username, password, xmData, origin, sd, ed);
        }
        
        public string DLL_ALICI_EKLE(string username, string password, string xmData, string _mesajXML, string _MsgTime, string _startDateXML, string origin, int msgcount, int SPCallNumber) {
            return base.Channel.DLL_ALICI_EKLE(username, password, xmData, _mesajXML, _MsgTime, _startDateXML, origin, msgcount, SPCallNumber);
        }
        
        public void sendSMSbyInteractive(string ACODE, string UCODE, string Message, string senderGSM) {
            base.Channel.sendSMSbyInteractive(ACODE, UCODE, Message, senderGSM);
        }
        
        public Dhmi.Web.SmsService.SmsSonuc sendSingleSMSobj(string username, string password, string numbers, string message, string origin, string sd, string ed) {
            return base.Channel.sendSingleSMSobj(username, password, numbers, message, origin, sd, ed);
        }
        
        public Dhmi.Web.SmsService.SmsSonuc sendNtoNSMSobjobjeski(string username, string password, string xmData, string origin, string sd, string ed) {
            return base.Channel.sendNtoNSMSobjobjeski(username, password, xmData, origin, sd, ed);
        }
        
        public Dhmi.Web.SmsService.SmsSonuc sendNtoNSMSobj(string username, string password, string xmData, string origin, string sd, string ed) {
            return base.Channel.sendNtoNSMSobj(username, password, xmData, origin, sd, ed);
        }
        
        public Dhmi.Web.SmsService.Kisi GetUserInfo(string username, string password) {
            return base.Channel.GetUserInfo(username, password);
        }
        
        public Dhmi.Web.SmsService.KisiAlt[] GetSubUserList(string username, string password) {
            return base.Channel.GetSubUserList(username, password);
        }
    }
}
